version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
  post_build:
    on-failure: ABORT
    commands:
      - echo BUILD COMPLETED!
      - echo EXECUTAR E2E
      - curl -X POST 'https://api.github.com/repos/ZupIT/itau-supernova-tests/dispatches' -H 'Accept: application/vnd.github.everest-preview+json' -i -u $TOKEN --data '{"event_type": "Start E2E Supernova", "client_payload": { "repository": "teste-repo" }}'
      - echo ACABOU
